# Generated by Django 2.2.6 on 2019-11-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsJF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='image1',
        ),
    ]
