# Generated by Django 2.2.6 on 2019-11-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsJF', '0002_auto_20191120_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary_image',
            new_name='summary',
        ),
    ]
