# Generated by Django 2.2.7 on 2019-11-28 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogJF', '0002_auto_20191127_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 18, 8, 31, 381463)),
        ),
    ]
