# Generated by Django 2.2.7 on 2019-11-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogJF', '0003_auto_20191127_1808'),
        ('blogJF', '0002_auto_20191128_0007'),
    ]

    operations = [
    ]
