# Generated by Django 2.2.7 on 2019-11-28 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogJF', '0004_merge_20191128_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 0, 10, 50, 999758)),
        ),
    ]
